version: "3"
services:
  subweb:
    image: "aenstan/subweb:latest"
    container_name: subweb
    restart: always
    ports: 
      - "10086:80"

  subconverter:
    image: "aenstan/subconverter:latest"
    container_name: subconverter
    restart: always
    ports: 
      - "25500:25500"
      
  myurls:
    image: "aenstan/myurls:latest"
    container_name: myurls
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - myurls-redis
    entrypoint: ["/app/myurls", "-domain", "s.aenstan.xyz", "-conn", "myurls-redis:6379", "-ttl", "365"]
  
  myurls-redis:
    image: "redis:5"
    container_name: myurls-redis
    restart: always
    expose:
      - "6379"
      
  caddy:
    image: "abiosoft/caddy"
    container_name: caddy
    restart: always
    network_mode: "my-network"
    environment:
      - TZ=Asia/Shanghai
      - agree
      - email admin@gmail.com
      - ACME_AGREE=true
      - CADDYPATH=/etc/caddycerts
    volumes:
      - "/root/caddy/certs:/etc/caddycerts"
      - "/root/caddy/Caddyfile:/etc/Caddyfile"
    ports:
      - "80:80"
      - "443:443"

